### ISSUE TITLE
network delay 추가

### ISSUE THREAD

**Issue by hea9549** [it-chain/avengers#12]
현재 어벤져스 노드(프로세스) 간 데이터처리에 딜레이가 없어요!
실제 네트워크 환경에서는 노드와 노드 즉 프로세스와 프로세스 사이에 딜레이가있어서
이로인해 발생하는 오류를 잡아보기위해
의도적으로 network delay를 추가하는 기능이 있으면 좋을것 같습니다.
~.setDelay(0.1) => 외부 메세지 도착시 0.1ms 딜레이 후 작동 이런식으로 기능 추가가 있어야 될 것 같아요

**Comment by frontalnh** [comment]
오호 좋네요 반영하겠습니다 ㅋㅋㅋ
